### ISSUE TITLE
Considered Rcpp?

### ISSUE THREAD

**Issue by Ironholds** [jayjacobs/tldextract#3]
I'm wondering if this would be any faster in C++; looked at it?

**Comment by jayjacobs** [comment]
It may be.  The version I released was as optimized as I could get it, but perhaps an Rcpp version could improve it even more. Is that something you’d want to explore?

**Comment by Ironholds** [comment]
Totally! Actually I was thinking of including this functionality (or: similar functionality) in [urltools](https://github.com/Ironholds/urltools), since it seems like a logical place for it to live, with an Rcpp backend. I'll see what I come up with and whether it makes sense to include it there or incorporate it here :)

**Comment by jayjacobs** [comment]
@hrbrmstr has also tossed out the idea of wrapping https://github.com/stricaud/faup in R.

**Comment by Ironholds** [comment]
Yeah, he poked me about that too; I'm planning on digging into it early next week. It looks pretty good but I'm fairly cautious at using Someone Else's C (to paraphrase Quinn Norton, C is good for two things: beautifully efficient code, and horrific memory leaks)

**Comment by Ironholds** [comment]
Actually it looks like the fastest C++ I can come up with without using C++11 to get the <regex> library is...well, four times slower than the R. Neat!
