### ISSUE TITLE
Together, we shall be more powerful than apart!

### ISSUE THREAD

**Issue by Ironholds** [jayjacobs/tldextract#5]
Hey Jay!

What would you think if we smushed tldextract into urltools? ;)

**Comment by jayjacobs** [comment]
I like that idea!  Did you want to integrate it or should I take a stab? then I'll update my repo to say it's merged.

- Jay

**Comment by Ironholds** [comment]
Want me to? I can standardise the formatting and naming. I was also thinking of, e.g., adding in a just-the-TLDs dataset and some other stuff.

(I've actually already got most of the stuff in /some/ form - tried to write a C++ analogue. It just turned out to be 4 times slower than R. Vectorised C rocks, yo!)

**Comment by Ironholds** [comment]
Okay; functionality now merged! Check out urltools::suffix_extract :). Still need to write a whole bunch of unit tests, but things otherwise seem to be functioning as expected.
